config/routes.rb
Rails.application.routes.draw do
  get '/flights/search/:query/:value' => 'flights#search'

  resources :reservations
  resources :airplanes
  resources :flights
  devise_for :users
  get '/users' => 'users/index#index'
  root to: 'pages#home';
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airplane, :optional => true
  has_many :reservations
  has_many :users, through: :reservations
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :flight, :optional => true
  belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :revervations
  has_many :flights, through: :revervations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  
  def index
    @airplanes = Airplane.all
  end

  def show
    @airplane = Airplane.find params[:id]
  end

  def new
    @airplane = Airplane.new
  end

  def create
    airplane = Airplane.new strong_params
    airplane.save
    redirect_to airplanes_path
  end

  def edit
    @airplane = Airplane.find params[:id]
  end

  def update
    airplane = Airplane.find params[:id]
    airplane.update strong_params
    redirect_to airplanes_path
  end

  def destroy
    airplane = Airplane.find params[:id]
    airplane.destroy

    redirect_to airplanes_path
  end

  private
  def strong_params
    params.require(:airplane).permit(:model, :rows, :columns)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def search
    @flights = Flight.where("#{params[:query]} = '#{params[:value]}'")
  end

  def index
    @flights = Flight.all
  end

  def show
    @flight = Flight.find params[:id]
    @flight_json = [@flight]
  end

  def new
    @flight = Flight.new
  end

  def create
    flight = Flight.create strong_params
    redirect_to flights_path
  end

  def edit
    @flight = Flight.find params[:id]
  end

  def update
    flight = Flight.find params[:id]
    flight.update strong_params
    redirect_to flights_path
  end

  def destroy
    flight = Flight.find params[:id]
    flight.destroy

    redirect_to flights_path
  end

  private
  def strong_params
    params.require(:flight).permit(:flight_number, :origin, :destination, :date, :airplane_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def show
    @reservation = Reservation.find params[:id]
  end

  def create
    @reservation = Reservation.create strong_params
    flight = @reservation.flight
    flight.booked_seats.push([@reservation.row, @reservation.column])
    flight.save

    redirect_to @reservation
  end

  private
  def strong_params
    params.permit(:row, :column, :flight_id, :user_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/index_controller.rb
class Users::IndexController < ApplicationController
  def index
    @users = User.all
    render 'devise/index.html.erb'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flight_helper.rb
module FlightHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/airplanes/_form.html.erb
<%= form_for @airplane do |f| %>
  <div>
    <%= f.label :model%>
    <%= f.text_field :model %>
  </div>

  <div>
    <%= f.label :rows%>
    <%= f.text_field :rows %>
  </div>

  <div>
    <%= f.label :columns%>
    <%= f.text_field :columns %>
  </div>

  <%= f.submit %>
<% end %>

app/views/airplanes/edit.html.erb
<h2>Edit Airplane</h2>

<%= render 'form' %>

app/views/airplanes/index.html.erb
<h1>Airplanes#index</h1>

<%= link_to 'New', new_airplane_path %>
<% @airplanes.each do |a| %>
  <div>
    <%= a.id %>
    <%= a.model %>
    <%= a.rows %>
    <%= a.columns %>

    <div class="controls">
      <%= link_to 'View', a %>
      <%= link_to 'Edit', edit_airplane_path(a.id) %>
      <%= link_to 'Delete', a, :method=>'delete' %>
    </div>
  </div>
<% end %>

app/views/airplanes/new.html.erb
<h2>New Airplane</h2>

<%= render 'form' %>

app/views/airplanes/show.html.erb
<div>
  <%= @airplane.id %>
</div>

<div>
  <%= @airplane.model %>
</div>

<div>
  <%= @airplane.rows %>
</div>

<div>
  <%= @airplane.columns %>
</div>

<div class="controls">
  <%= link_to 'Edit', edit_airplane_path %>
  <%= link_to 'Delete', @airplane, :method=>'delete' %>
</div>

app/views/flights/_form.html.erb
<%= form_for @flight do |f| %>
  <div>
    <%= f.label :flight_number%>
    <%= f.text_field :flight_number, :required=>'true' %>
  </div>

  <div>
    <%= f.label :origin%>
    <%= f.text_field :origin, :required=>'true' %>
  </div>

  <div>
    <%= f.label :destination%>
    <%= f.text_field :destination, :required=>'true' %>
  </div>

  <div>
    <%= f.label :date%>
    <%= f.text_field :date, :required=>'true' %>
  </div>


  <div>
    <%= f.label :airplane_id%>
    <%= f.select :airplane_id, Airplane.pluck(:model, :id), :required=>'true' %>
  </div>

  <%= f.submit %>
<% end %>

app/views/flights/edit.html.erb
<h1>Flight#edit</h1>

<%= render 'form' %>

app/views/flights/index.html.erb
<h1>Flights#index</h1>

<%= link_to 'New', new_flight_path %>

<% @flights.each do |f| %>
  <div>
    <%= f.id %>
    <%= f.flight_number %>
    <%= f.origin %>
    <%= f.destination %>
    <%= f.date %>
    <%= f.airplane.model %>

    <div class="controls">
      <%= link_to 'View', f %>
      <%= link_to 'Edit', edit_flight_path(f.id) %>
      <%= link_to 'Delete', f, :method=>'delete' %>
    </div>
  </div>
<% end %>

app/views/flights/new.html.erb
<h1>Flight#new</h1>

<%= render 'form' %>

app/views/flights/search.html.erb
<% @flights.each do |f| %>
<%= f.origin %>
<% end %>

app/views/flights/show.html.erb
<h1>Flight#show</h1>

<div>
  <%= @flight.id %>
</div>

<div>
  <%= @flight.flight_number %>
</div>

<div>
  <%= @flight.origin %>
</div>

<div>
  <%= @flight.destination %>
</div>

<div>
  <%= @flight.date %>
</div>

<div>
  <%= @flight.airplane.model %>
</div>

<% for i in 1..@flight.airplane.rows do %>
  <% for j in 1..@flight.airplane.columns do  %>
    <%= form_tag reservations_path do %>
      <input type="hidden" name="flight_id" value=<%= @flight.id %>>
      <input type="hidden" name="user_id" value="1">
      <input type="hidden" name="row" value=<%= i %>>
      <input type="hidden" name="column" value=<%= j %>>
      <input type="submit" value="row: <%= i %>, col: <%= j %>">
    <% end %>
  <% end %>
<% end %>

<div class="controls">
  <%= link_to 'Edit', edit_flight_path %>
  <%= link_to 'Delete', @flight, :method=>'delete' %>
</div>

app/views/reservations/show.html.erb
<%= @reservation.id %>
<%= @reservation.row %>
<%= @reservation.column %>
<%= @reservation.flight.id %>
<%= @reservation.flight.airplane.model %>